defaults:
  - train_transform: empty
  - test_transform: empty
  - _self_

name: MultidisasterEarth_${dataset.embedding_name}
full_batch_size: 512
cond_dim: 1024
eval_batch_size: 4096
output_type: emb
embedding_name: dinov2

train_dataset:
  _partial_: true
  _target_: plonk.data.data.MultidisasterEarth30
  split: train
  root: ${data_dir}/data/MultiDisaster_20250320
  embedding_name: ${dataset.embedding_name}

val_dataset:
  _partial_: true
  _target_: plonk.data.data.MultidisasterEarth30
  root: ${data_dir}/data/MultiDisaster_20250320
  split: test
  embedding_name: ${dataset.embedding_name}

test_dataset:
  _partial_: true
  _target_: plonk.data.data.MultidisasterEarth30
  split: test
  root: ${data_dir}/data/MultiDisaster_20250320
  embedding_name: ${dataset.embedding_name}
